/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Talent4StartupsRouteImport } from './routes/talent-4-startups'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as InnovationHubRouteImport } from './routes/innovation-hub'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const Talent4StartupsRoute = Talent4StartupsRouteImport.update({
  id: '/talent-4-startups',
  path: '/talent-4-startups',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationHubRoute = InnovationHubRouteImport.update({
  id: '/innovation-hub',
  path: '/innovation-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/innovation-hub': typeof InnovationHubRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/talent-4-startups': typeof Talent4StartupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/innovation-hub': typeof InnovationHubRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/talent-4-startups': typeof Talent4StartupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/innovation-hub': typeof InnovationHubRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/talent-4-startups': typeof Talent4StartupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/innovation-hub'
    | '/partners'
    | '/programs'
    | '/projects'
    | '/services'
    | '/talent-4-startups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/innovation-hub'
    | '/partners'
    | '/programs'
    | '/projects'
    | '/services'
    | '/talent-4-startups'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/innovation-hub'
    | '/partners'
    | '/programs'
    | '/projects'
    | '/services'
    | '/talent-4-startups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  InnovationHubRoute: typeof InnovationHubRoute
  PartnersRoute: typeof PartnersRoute
  ProgramsRoute: typeof ProgramsRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  Talent4StartupsRoute: typeof Talent4StartupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent-4-startups': {
      id: '/talent-4-startups'
      path: '/talent-4-startups'
      fullPath: '/talent-4-startups'
      preLoaderRoute: typeof Talent4StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-hub': {
      id: '/innovation-hub'
      path: '/innovation-hub'
      fullPath: '/innovation-hub'
      preLoaderRoute: typeof InnovationHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  InnovationHubRoute: InnovationHubRoute,
  PartnersRoute: PartnersRoute,
  ProgramsRoute: ProgramsRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  Talent4StartupsRoute: Talent4StartupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
